In [115]:
import numpy as np
import matplotlib.pyplot as plt

In [17]:
mat=np.array(range(1,10))
print("Number of dimensions=\t",mat.ndim)
print("Shape=\t",mat.shape)
print(mat)

Number of dimensions=	 1
Shape=	 (9,)
[1 2 3 4 5 6 7 8 9]


In [16]:
mat=np.array(range(1,10)).reshape(3,3)
print("Number of dimensions=\t",mat.ndim)
print("Shape=\t",mat.shape)
print(mat)

Number of dimensions=	 2
Shape=	 (3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
mat=np.array(range(1,10)).reshape(3,3,-1,1)
print("Number of dimensions=\t",mat.ndim)
print("Shape=\t",mat.shape)


Number of dimensions=	 4
Shape=	 (3, 3, 1, 1)


In [23]:
mat=np.array(range(1,21))
print("Number of dimensions=\t",mat.ndim)
print("Shape=\t",mat.shape)
print(mat)
mat.reshape((20,-1))

Number of dimensions=	 1
Shape=	 (20,)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20]])

In [24]:
print("Number of dimensions=\t",mat.ndim)
print("Shape=\t",mat.shape)
print(mat)
mat.reshape((-1,20))

Number of dimensions=	 1
Shape=	 (20,)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20]])

In [25]:
print("Number of dimensions=\t",mat.ndim)
print("Shape=\t",mat.shape)
print(mat)
mat.reshape((5,-1))

Number of dimensions=	 1
Shape=	 (20,)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [26]:
print("Number of dimensions=\t",mat.ndim)
print("Shape=\t",mat.shape)
print(mat)
mat.reshape((-1,5))

Number of dimensions=	 1
Shape=	 (20,)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [30]:
print("Number of dimensions=\t",mat.ndim)
print("Shape=\t",mat.shape)
print(mat)
mat.reshape((2,-1))

Number of dimensions=	 1
Shape=	 (20,)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [47]:
mat=np.array(['1',1,'0','2.5'])

In [48]:
mat.astype(float)

array([1. , 1. , 0. , 2.5])

In [93]:
mat=np.array(range(1,21))
print("Number of dimensions=\t",mat.ndim)
print("Shape=\t",mat.shape)

mat=mat.reshape((2,2,5))
print(mat)

Number of dimensions=	 1
Shape=	 (20,)
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [94]:
print(mat)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [97]:
mat[1][0][2]

np.int64(13)

In [99]:
mat=np.array(range(1,21))
print("Number of dimensions=\t",mat.ndim)
print("Shape=\t",mat.shape)

mat=mat.reshape((4,5))
print(mat)

Number of dimensions=	 1
Shape=	 (20,)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [103]:
mat=np.array(range(1,21))


mat=mat.reshape((4,5))
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [104]:
print(mat.T)

[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


In [107]:
mat=np.ones((3,3))

In [130]:
# plt.plot(np.linspace(0,1))
np.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [119]:
np.full((3,3),6)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [150]:
# np.random.seed(42)
np.random.random((3,3))

array([[0.43194502, 0.29122914, 0.61185289],
       [0.13949386, 0.29214465, 0.36636184],
       [0.45606998, 0.78517596, 0.19967378]])

In [137]:
np.empty((3,3))

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501]])

In [167]:
ar=[1,1,1,2,2,3,3,3,3,4,5,6]

In [168]:
np.random.choice(ar,p=[])

np.int64(3)

In [201]:
# np.random.choice??

In [178]:
aa_milne_arr = ['pooh', 'rabbit', 'piglet', 'Christopher']
for _ in range(10):
    print(np.random.choice(aa_milne_arr,20, p=[0.5, 0.1, 0.1, 0.3]))

['pooh' 'Christopher' 'piglet' 'pooh' 'pooh' 'pooh' 'pooh' 'Christopher'
 'piglet' 'Christopher' 'pooh' 'pooh' 'Christopher' 'Christopher' 'rabbit'
 'Christopher' 'pooh' 'rabbit' 'pooh' 'pooh']
['pooh' 'pooh' 'piglet' 'pooh' 'rabbit' 'Christopher' 'pooh' 'pooh'
 'Christopher' 'pooh' 'pooh' 'pooh' 'pooh' 'Christopher' 'Christopher'
 'piglet' 'Christopher' 'Christopher' 'pooh' 'Christopher']
['rabbit' 'Christopher' 'Christopher' 'pooh' 'pooh' 'pooh' 'pooh'
 'Christopher' 'Christopher' 'pooh' 'rabbit' 'pooh' 'pooh' 'pooh' 'pooh'
 'Christopher' 'pooh' 'rabbit' 'Christopher' 'pooh']
['Christopher' 'Christopher' 'pooh' 'pooh' 'pooh' 'pooh' 'pooh' 'piglet'
 'rabbit' 'pooh' 'pooh' 'Christopher' 'pooh' 'pooh' 'pooh' 'Christopher'
 'pooh' 'piglet' 'Christopher' 'pooh']
['Christopher' 'pooh' 'piglet' 'piglet' 'rabbit' 'pooh' 'Christopher'
 'pooh' 'pooh' 'pooh' 'rabbit' 'piglet' 'pooh' 'rabbit' 'pooh' 'piglet'
 'pooh' 'piglet' 'pooh' 'Christopher']
['pooh' 'pooh' 'pooh' 'Christopher' 'Christopher'

In [195]:
a2=np.random.random((3,3))
np.savez("C:/Users/Mohammed/Alex8/output.npz",environment=mat,mat2=a2)

In [190]:
with np.load('output.npz') as x:
    print(x['mat2'])

[[0.79579267 0.89000534 0.33799516]
 [0.37558295 0.09398194 0.57828014]
 [0.03594227 0.46559802 0.54264463]]


In [204]:
a2
a=np.full((2,2),6)

In [206]:
ar=np.array([1,3,4,5,0])

In [211]:
np.all(ar>=1)

np.False_

In [212]:
a3=np.array([2,4,3,4,10])

In [216]:
np.where(a3>3)

(array([1, 3, 4]),)

In [217]:
a3=np.arange(1,10).reshape(3,3)

In [218]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [219]:
v=np.array([.5,.2,.9])

In [221]:
print(a3+v)

[[1.5 2.2 3.9]
 [4.5 5.2 6.9]
 [7.5 8.2 9.9]]


In [224]:
a3.size

9

In [225]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [227]:
np.argsort(arr)

array([1, 0, 3, 5, 2, 6, 4, 7])

In [236]:
np.flip(a3)

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [239]:
a3.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [256]:
a3=np.arange(1,10).reshape(3,3)

In [257]:
a4=a3.copy()

In [258]:
a4[0,1]=50

In [259]:
a4

array([[ 1, 50,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [260]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [279]:
ar=np.zeros((9,9))

In [287]:
r=.1
for i in range(ar.shape[0]):
    for j in range(ar.shape[1]):
        ar[i,j]+=r
        r+=.1

In [288]:
ar.shape[0]

9

In [289]:
die=np.arange(1,7)

In [290]:
die

array([1, 2, 3, 4, 5, 6])

In [301]:
for i in range(10):
    print(np.array(np.random.choice(die,2)))

[5 1]
[3 1]
[6 1]
[1 6]
[4 1]
[6 5]
[3 3]
[1 4]
[4 5]
[1 3]


In [302]:
np.full((3,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [308]:
ar.dot(ar)

array([[ 198.45,  202.5 ,  206.55,  210.6 ,  214.65,  218.7 ,  222.75,
         226.8 ,  230.85],
       [ 468.18,  479.52,  490.86,  502.2 ,  513.54,  524.88,  536.22,
         547.56,  558.9 ],
       [ 737.91,  756.54,  775.17,  793.8 ,  812.43,  831.06,  849.69,
         868.32,  886.95],
       [1007.64, 1033.56, 1059.48, 1085.4 , 1111.32, 1137.24, 1163.16,
        1189.08, 1215.  ],
       [1277.37, 1310.58, 1343.79, 1377.  , 1410.21, 1443.42, 1476.63,
        1509.84, 1543.05],
       [1547.1 , 1587.6 , 1628.1 , 1668.6 , 1709.1 , 1749.6 , 1790.1 ,
        1830.6 , 1871.1 ],
       [1816.83, 1864.62, 1912.41, 1960.2 , 2007.99, 2055.78, 2103.57,
        2151.36, 2199.15],
       [2086.56, 2141.64, 2196.72, 2251.8 , 2306.88, 2361.96, 2417.04,
        2472.12, 2527.2 ],
       [2356.29, 2418.66, 2481.03, 2543.4 , 2605.77, 2668.14, 2730.51,
        2792.88, 2855.25]])